#!/usr/bin/env bash

function ci_install {
	local cinder_drivers_path='cinder/volume/drivers/nexenta'
	local cinder_unit_tests_path='cinder/tests/unit/volume/drivers/nexenta'
	local manila_drivers_path='manila/share/drivers/nexenta'

	if [[ "$NEXENTA_CI_TYPE" == "external" ]]; then
		return
	fi

	if is_service_enabled cinder; then
		git_clone $NEXENTA_CINDER_REPO $NEXENTA_CINDER_DIR $NEXENTA_BRANCH

		if [[ -d "$NEXENTA_CINDER_DIR/$cinder_drivers_path" ]]; then
			rm -rf $CINDER_DIR/$cinder_drivers_path
			cp -prv $NEXENTA_CINDER_DIR/$cinder_drivers_path \
			        $CINDER_DIR/$cinder_drivers_path
		fi

		if [[ -d "$NEXENTA_CINDER_DIR/$cinder_unit_tests_path" ]]; then
			rm -rf $CINDER_DIR/$cinder_unit_tests_path
			cp -prv $NEXENTA_CINDER_DIR/$cinder_unit_tests_path \
			        $CINDER_DIR/$cinder_unit_tests_path
		fi

		case "$CI_BACKEND" in
		ns4_iscsi|ns4_nfs|ns5_iscsi|ns5_nfs)
			rm -rfv $CINDER_DIR/$cinder_drivers_path/*edge*
			rm -rfv $CINDER_DIR/$cinder_unit_tests_path/*edge*
			;;
		*)
			;;
		esac
	fi

	if is_service_enabled manila; then
		git_clone $NEXENTA_MANILA_REPO $NEXENTA_MANILA_DIR $NEXENTA_BRANCH

		if [[ -d "$NEXENTA_MANILA_DIR/$manila_drivers_path" ]]; then
			rm -rf $MANILA_DIR/$manila_drivers_path
			cp -prv $NEXENTA_MANILA_DIR/$manila_drivers_path \
			        $MANILA_DIR/$manila_drivers_path
		fi
	fi
}

function ci_extra {
	local etc_apache lib_apache
	local lso_apache lso_python
	local pkg_python mod_python
	local key_type key_file
	local tnt pid gid

	case "$CI_BRANCH" in
	icehouse|juno|kilo|liberty|mitaka|newton)
		ci_test_config
		;;
	*)
		;;
	esac

	if is_service_enabled horizon; then
		install_package apache2-dev
		lib_apache=$(apxs -q exp_libexecdir)
		lso_apache=$(ldd $lib_apache/mod_wsgi.so | awk '/libpython/{print $1}')
		lso_python=$($PYTHON $CIDIR/scripts/get_python_soname.py)
		if [[ "$lso_apache" != "$lso_python" ]]; then
			sudo $PYTHON -m pip install mod_wsgi
			pkg_python=$($PYTHON $CIDIR/scripts/get_python_packages.py)
			mod_python=$(find $pkg_python -type f -name 'mod_wsgi*.so')
			etc_apache=$(apxs -q exp_sysconfdir)
			sudo tee $etc_apache/mods-available/wsgi.load <<-EOF
			LoadModule wsgi_module $mod_python
			EOF
			sudo systemctl restart apache2
		fi
	fi

	if is_service_enabled nova; then
		case "$VIRT_DRIVER" in
		libvirt)
			if [[ -n "$QEMU_CONF" && -f "$QEMU_CONF" ]]; then
				echo 'security_driver = "none"' | \
					sudo tee -a $QEMU_CONF
				if [[ -n "$LIBVIRT_DAEMON" ]]; then
					restart_service $LIBVIRT_DAEMON
				fi
			fi
			;;
		*)
			;;
		esac

		if [[ ! -e "$TOP_DIR/userrc_early" ]]; then
			return
		fi

		source $TOP_DIR/userrc_early

		for key_type in rsa dsa ecdsa ed25519; do
			key_file="$HOME/.ssh/id_${key_type}"

			if [[ ! -r "$key_file" ]]; then
				ssh-keygen -N '' -t $key_type -f $key_file
			fi

			key_file+='.pub'

			if [[ -r "$key_file" ]]; then
				openstack keypair create --public-key $key_file $HOSTNAME
				break
			fi
		done

		for tnt in admin demo; do
			pid=$(openstack project list | awk '{if ($4=="'$tnt'") {print $2}}')

			if [[ -z "$pid" ]]; then
				continue
			fi

			gid=$(openstack security group list | awk '{if ($(NF-1)=="'$pid'") {print $2}}')

			if [[ -z "$gid" ]]; then
				continue
			fi

			openstack security group rule create --proto icmp --dst-port 0 $gid
			openstack security group rule create --proto tcp --dst-port 22 $gid
		done
	fi
}

function ci_test_config {
	if is_service_enabled tempest; then
		if is_service_enabled nova; then
			iniset $TEMPEST_CONFIG compute build_interval 5
		fi

		if is_service_enabled cinder; then
			case "$CI_BRANCH" in
			ocata|pike)
				iniset $TEMPEST_CONFIG volume catalog_type volumev3
				;;
			*)
				;;
			esac

			case "$CI_BACKEND" in
			ns5_iscsi|ns5_nfs)
				iniset $TEMPEST_CONFIG volume-feature-enabled consistency_group True
				;;
			*)
				;;
			esac

			case "$CI_BRANCH" in
			pike|queens|rocky|stein|train|master)
				iniset $TEMPEST_CONFIG volume-feature-enabled volume_revert True
				;;
			*)
				;;
			esac

			case "$CI_BRANCH" in
			ocata|pike|queens|rocky|stein|train|master)
				case "$CI_BACKEND" in
				ns5_iscsi|ns5_nfs)
					iniset $TEMPEST_CONFIG volume manage_volume_ref "source-name, volume-%s"
					iniset $TEMPEST_CONFIG volume manage_snapshot_ref "source-name, snapshot-%s"
					;;
				*)
					;;
				esac
				;;
			*)
				;;
			esac
		fi

		if is_service_enabled manila; then
			_max_api_ver=$(awk '/^_MAX_API_VERSION/{print $NF}' $MANILA_DIR/manila/api/openstack/api_version_request.py)
			if [[ -n "$_max_api_ver" ]]; then
				iniset $TEMPEST_CONFIG share max_api_microversion $_max_api_ver
			fi

			iniset $TEMPEST_CONFIG share capability_storage_protocol NFS
			iniset $TEMPEST_CONFIG share capability_snapshot_support True
			iniset $TEMPEST_CONFIG share capability_create_share_from_snapshot_support True
			iniset $TEMPEST_CONFIG share capability_revert_to_snapshot_support True
			iniset $TEMPEST_CONFIG share capability_mount_snapshot_support False
			iniset $TEMPEST_CONFIG share backend_names $MANILA_ENABLED_BACKENDS
			iniset $TEMPEST_CONFIG share multi_backend True
			iniset $TEMPEST_CONFIG share multitenancy_enabled False
			iniset $TEMPEST_CONFIG share enable_protocols nfs
			iniset $TEMPEST_CONFIG share enable_ip_rules_for_protocols nfs
			iniset $TEMPEST_CONFIG share enable_ro_access_level_for_protocols nfs
			iniset $TEMPEST_CONFIG share run_mount_snapshot_tests False
			iniset $TEMPEST_CONFIG share run_quota_tests True
			iniset $TEMPEST_CONFIG share run_extend_tests True
			iniset $TEMPEST_CONFIG share run_revert_to_snapshot_tests True
			iniset $TEMPEST_CONFIG share run_share_group_tests True
			iniset $TEMPEST_CONFIG share run_snapshot_tests True
			iniset $TEMPEST_CONFIG share run_consistency_group_tests False
			iniset $TEMPEST_CONFIG share run_replication_tests False
			iniset $TEMPEST_CONFIG share run_migration_tests False

			case "$CI_BACKEND" in
			ns4_manila)
				iniset $TEMPEST_CONFIG share run_manage_unmanage_tests True
				iniset $TEMPEST_CONFIG share run_manage_unmanage_snapshot_tests False
				iniset $TEMPEST_CONFIG share run_shrink_tests False
				;;
			ns5_manila)
				iniset $TEMPEST_CONFIG share run_manage_unmanage_tests False
				iniset $TEMPEST_CONFIG share run_manage_unmanage_snapshot_tests False
				iniset $TEMPEST_CONFIG share run_shrink_tests True
				;;
			*)
				;;
			esac
		fi
	fi
}

function ci_clean {
	local mount_point

	iscsiadm -m node -u
	iscsiadm -m node --op delete

	for mount_point in $(df | awk '{if ($NF ~ "^'$CINDER_STATE_PATH'") print $NF}'); do
		sudo umount -f $mount_point && rmdir $mount_point
	done
}

function ci_unstack {
	ci_clean
}
