#!/usr/bin/env bash
#
# Configure the NexentaEdge iSCSI backend
#

NEXENTA_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ned_iscsi {
	local backend="$1"
	local prefix="NEXENTA_OPTGROUP_${backend}_"
	local deploy="False"
	local item

	for item in nexenta_iscsi_service nexenta_rest_address nexenta_client_address; do
		local env="$(set | awk '/^'$prefix$item'=/')"

		if [[ -z "$env" ]]; then
			deploy="True"
			break
		fi
	done

	if [[ "$deploy" == "True" ]]; then
		local space=${backend//_/-}

		sudo $CIDIR/scripts/nedge-k8.sh "$space"

		for item in .kube .minikube; do
			if [[ -d "$HOME/$item" ]]; then
				sudo chown -R $(id -un):$(id -gn) "$HOME/$item"
			fi
		done

		local "${prefix}nexenta_iscsi_service"="$space"
		local "${prefix}nexenta_rest_address"="$(ci_cip "$space" "${space}-mgmt")"
		local "${prefix}nexenta_client_address"="$(ci_cip "$space" "${space}-svc-iscsi-${space}")"
	fi

	for item in $(set | grep "^$prefix"); do
		local opt="${item#$prefix}"
		local name="${opt%%=*}"
		local value="${opt#*=}"

		iniset "$CINDER_CONF" "$backend" "$name" "$value"
	done
}

function cleanup_cinder_backend_ned_iscsi {
	ci_clean
	sudo $CIDIR/scripts/nedge-k8.sh clean
}

$NEXENTA_XTRACE
