#!/usr/bin/env bash
#
# Configure the NexentaStor4 iSCSI backend
#

_XTRACE_CI=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ns4_iscsi {
	local backend="$1"
	local prefix="CINDER_OPTGROUP_${backend}_"
	local item

	for item in $(set | grep "^$prefix"); do
		local opt="${item#$prefix}"
		local name="${opt%%=*}"
		local value="${opt#*=}"

		iniset "$CINDER_CONF" "$backend" "$name" "$value"
	done
}

function cleanup_cinder_backend_ns4_iscsi {
	ci_clean
}

$_XTRACE_CI
