#!/usr/bin/env bash
#
# Configure the NexentaStor4 NFS backend
#

NEXENTA_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ns4_nfs {
	declare backend=$1
	declare item
	declare -A opt
	declare -A NEXENTA_PREFIX

	opt[volume_driver]=NEXENTA_DRIVER
	opt[nas_mount_options]=NEXENTA_OPTIONS
	opt[nexenta_sparsed_volumes]=NEXENTA_SPARSED

	NEXENTA_PREFIX[$backend]="volumes"

	iniset $CINDER_CONF $backend volume_backend_name $backend
	iniset $CINDER_CONF $backend nexenta_shares_config \
		$CINDER_CONF_DIR/$backend.conf

	for item in "${!opt[@]}"; do
		declare -n var="${opt[$item]}[$backend]"

		if [[ -n "${var:-}" ]]; then
			iniset $CINDER_CONF $backend $item $var
		fi
	done

	printf "%s:/%s/%s/%s\t%s://%s:%s@%s:%d\n" \
		${NEXENTA_HOST[$backend]} ${NEXENTA_PREFIX[$backend]} \
		${NEXENTA_POOL[$backend]} ${NEXENTA_DATASET[$backend]} \
		${NEXENTA_REST_PROTO[$backend]} ${NEXENTA_REST_USER[$backend]} \
		${NEXENTA_REST_PASSWORD[$backend]} ${NEXENTA_HOST[$backend]} \
		${NEXENTA_REST_PORT[$backend]} >$CINDER_CONF_DIR/$backend.conf
}

function cleanup_cinder_backend_ns4_nfs {
	declare mount_point

	for mount_point in $CINDER_STATE_PATH/mnt/*; do
		sudo "umount -f $mount_point && rmdir $mount_point"
	done
}

$NEXENTA_XTRACE
