#!/usr/bin/env bash
#
# Configure the NexentaStor4 Manila backend
#

NEXENTA_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ns4_manila {
	declare backend=$1
	declare item share
	declare -A opt

	opt[share_driver]=NEXENTA_DRIVER
	opt[nexenta_host]=NEXENTA_REST_HOST
	opt[nexenta_pool]=NEXENTA_POOL
	opt[nexenta_nfs_share]=NEXENTA_DATASET
	opt[nexenta_thin_provisioning]=NEXENTA_SPARSED
	opt[nexenta_user]=NEXENTA_REST_USER
	opt[nexenta_password]=NEXENTA_REST_PASSWORD
	opt[nexenta_rest_port]=NEXENTA_REST_PORT
	opt[nexenta_rest_protocol]=NEXENTA_REST_PROTO

	iniset $MANILA_CONF $backend share_backend_name $backend
	iniset $MANILA_CONF $backend driver_handles_share_servers False

	for item in "${!opt[@]}"; do
		declare -n var="${opt[$item]}[$backend]"

		if [[ -n "${var:-}" ]]; then
			iniset $MANILA_CONF $backend $item $var
		fi
	done
}

function cleanup_cinder_backend_ns4_manila {
	declare mount_point

	for mount_point in $(df | awk 'if ($NF ~ "^'$CINDER_STATE_PATH'") print $NF}'); do
		sudo umount -f $mount_point && rmdir $mount_point
	done
}

$NEXENTA_XTRACE
