#!/usr/bin/env bash
#
# Configure the NexentaStor5 iSCSI backend
#

NEXENTA_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ns5_iscsi {
	set -x
	echo ' ====> configure_cinder_backend_ns5_iscsi'
	local backend=$1
	local prefix="NEXENTA_OPTGROUP_${backend}_"

	set | grep "^$prefix" | while read -r line; do
		opt=${line#$prefix}
		name=${opt%%=*}
		value=${opt##*=}
		iniset $CINDER_CONF $backend $name $value
	done
}

function cleanup_cinder_backend_ns5_iscsi {
	ci_clean
}

$NEXENTA_XTRACE
