#!/usr/bin/env bash
#
# Configure the NexentaStor5 NFS backend
#

_XTRACE_CI=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ns5_nfs {
	local backend="$1"
	local prefix="CINDER_OPTGROUP_${backend}_"
	local options=''
	local item

	for item in $(set | grep "^$prefix"); do
		local opt="${item#$prefix}"
		local name="${opt%%=*}"
		local value="${opt#*=}"

		case "$name" in
		nas_mount_options|nfs_mount_options)
			options="$value"
			;;
		*)
			iniset "$CINDER_CONF" "$backend" "$name" "$value"
			;;
		esac
	done

	if [[ -n "$options" ]]; then
		iniset "$CINDER_CONF" "$backend" 'nas_mount_options' "$options"
		iniset "$CINDER_CONF" "$backend" 'nfs_mount_options' "$options"
	fi
}

function cleanup_cinder_backend_ns5_nfs {
	ci_clean
}

$_XTRACE_CI
