#!/usr/bin/env bash
#
# Configure the NexentaStor5 NFS backend
#

NEXENTA_XTRACE=$(set +o | grep xtrace)
set +o xtrace

function configure_cinder_backend_ns5_nfs {
	local backend=$1
	local prefix="NEXENTA_OPTGROUP_${backend}_"

	for env in $(set | grep "^$prefix"); do
		opt=${env#$prefix}
		name=${opt%%=*}
		value=${opt##*=}
		iniset $CINDER_CONF $backend $name $value
	done
}

function cleanup_cinder_backend_ns5_nfs {
	ci_clean
}

$NEXENTA_XTRACE
